// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nagomi.Api.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nagomi.Api.Migrations
{
    [DbContext(typeof(NagomiDbContext))]
    [Migration("20260729104652_InitialPostgreSql")]
    partial class InitialPostgreSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nagomi.Api.Domain.Journey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActualActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActualArrivedAtDestinationAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActualArrivedAtOriginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActualCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActualPatientPickupAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentCancellationReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("CurrentCancellingParty")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsManuallyAdded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecurrenceException")
                        .HasColumnType("boolean");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderVisibleNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TransportRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("TransportRequestId", "ServiceDate", "Direction");

                    b.ToTable("journeys", (string)null);
                });

            modelBuilder.Entity("Nagomi.Api.Domain.JourneyStatusEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("CancellingParty")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ExternalResourceCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("JourneyId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("JourneyId", "OccurredAt");

                    b.ToTable("journey_status_events", (string)null);
                });

            modelBuilder.Entity("Nagomi.Api.Domain.TransportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContractCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrivateNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderVisibleNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("PublicId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasFilter("\"PublicId\" IS NOT NULL");

                    b.ToTable("transport_requests", (string)null);
                });

            modelBuilder.Entity("Nagomi.Api.Features.Audit.AuditChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PreviousValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Protection")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("AuditEntryId");

                    b.ToTable("audit_changes", (string)null);
                });

            modelBuilder.Entity("Nagomi.Api.Features.Audit.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ActorIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntityIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityIdentifier", "ReceivedAt");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("Nagomi.Api.Features.ReferenceData.HealthcareFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalDetails")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AutonomousCommunityCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Block")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Ccn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Codcnh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Door")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Floor")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("MunicipalityCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Number")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("OfficialAddressText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("SourceYear")
                        .HasColumnType("integer");

                    b.Property<string>("Staircase")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Street")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("Ccn")
                        .IsUnique()
                        .HasFilter("\"Ccn\" IS NOT NULL");

                    b.HasIndex("Codcnh")
                        .IsUnique()
                        .HasFilter("\"Codcnh\" IS NOT NULL");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Name", "MunicipalityCode");

                    b.ToTable("healthcare_facilities", (string)null);
                });

            modelBuilder.Entity("Nagomi.Api.Features.ReferenceData.IneAutonomousCommunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ine_autonomous_communities", (string)null);
                });

            modelBuilder.Entity("Nagomi.Api.Features.ReferenceData.IneMunicipality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AutonomousCommunityCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ProvinceCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProvinceCode");

                    b.ToTable("ine_municipalities", (string)null);
                });

            modelBuilder.Entity("Nagomi.Api.Features.ReferenceData.IneProvince", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AutonomousCommunityCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AutonomousCommunityCode");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ine_provinces", (string)null);
                });

            modelBuilder.Entity("Nagomi.Api.Features.ReferenceData.TransportReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("transport_reasons", (string)null);
                });

            modelBuilder.Entity("Nagomi.Api.Domain.Journey", b =>
                {
                    b.HasOne("Nagomi.Api.Domain.TransportRequest", null)
                        .WithMany("Journeys")
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nagomi.Api.Domain.LocationSnapshot", "Destination", b1 =>
                        {
                            b1.Property<Guid>("JourneyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AdditionalDetails")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Block")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("Door")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("FacilityPublicId")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<string>("Floor")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<decimal?>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)");

                            b1.Property<decimal?>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)");

                            b1.Property<string>("Municipality")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)");

                            b1.Property<string>("MunicipalityCode")
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)");

                            b1.Property<string>("Name")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("Number")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("Observations")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("OfficialCode")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Phone")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Province")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)");

                            b1.Property<string>("ProvinceCode")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)");

                            b1.Property<string>("Staircase")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("Street")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.HasKey("JourneyId");

                            b1.ToTable("journeys");

                            b1.WithOwner()
                                .HasForeignKey("JourneyId");
                        });

                    b.OwnsOne("Nagomi.Api.Domain.LocationSnapshot", "Origin", b1 =>
                        {
                            b1.Property<Guid>("JourneyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AdditionalDetails")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Block")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("Door")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("FacilityPublicId")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<string>("Floor")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<decimal?>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)");

                            b1.Property<decimal?>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)");

                            b1.Property<string>("Municipality")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)");

                            b1.Property<string>("MunicipalityCode")
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)");

                            b1.Property<string>("Name")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("Number")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("Observations")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("OfficialCode")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Phone")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Province")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)");

                            b1.Property<string>("ProvinceCode")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)");

                            b1.Property<string>("Staircase")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("Street")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.HasKey("JourneyId");

                            b1.ToTable("journeys");

                            b1.WithOwner()
                                .HasForeignKey("JourneyId");
                        });

                    b.OwnsOne("Nagomi.Api.Domain.TransportRequirements", "Requirements", b1 =>
                        {
                            b1.Property<Guid>("JourneyId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("BariatricRequired")
                                .HasColumnType("boolean");

                            b1.Property<bool>("CompanionRequired")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsolationRequired")
                                .HasColumnType("boolean");

                            b1.Property<bool>("MedicalStaffRequired")
                                .HasColumnType("boolean");

                            b1.Property<string>("Mobility")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<decimal?>("OxygenConcentrationPercent")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)");

                            b1.Property<decimal?>("OxygenFlowLitresPerMinute")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)");

                            b1.Property<bool>("RequiresOxygen")
                                .HasColumnType("boolean");

                            b1.Property<bool>("StairsAssistanceRequired")
                                .HasColumnType("boolean");

                            b1.HasKey("JourneyId");

                            b1.ToTable("journeys");

                            b1.WithOwner()
                                .HasForeignKey("JourneyId");
                        });

                    b.OwnsOne("Nagomi.Api.Domain.JourneySchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("JourneyId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("AppointmentAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("PickupTimePending")
                                .HasColumnType("boolean");

                            b1.Property<DateTimeOffset?>("ScheduledPickupAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset>("ScheduledStartAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("JourneyId");

                            b1.ToTable("journeys");

                            b1.WithOwner()
                                .HasForeignKey("JourneyId");
                        });

                    b.Navigation("Destination")
                        .IsRequired();

                    b.Navigation("Origin")
                        .IsRequired();

                    b.Navigation("Requirements")
                        .IsRequired();

                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("Nagomi.Api.Domain.JourneyStatusEvent", b =>
                {
                    b.HasOne("Nagomi.Api.Domain.Journey", null)
                        .WithMany("StatusEvents")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nagomi.Api.Domain.TransportRequest", b =>
                {
                    b.OwnsOne("Nagomi.Api.Domain.PatientDetails", "Patient", b1 =>
                        {
                            b1.Property<Guid>("TransportRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DocumentNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)");

                            b1.Property<string>("HealthCardNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("LastName")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("Phone")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("TransportRequestId");

                            b1.ToTable("transport_requests");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestId");
                        });

                    b.OwnsOne("Nagomi.Api.Domain.RecurrencePattern", "Recurrence", b1 =>
                        {
                            b1.Property<Guid>("TransportRequestId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("date");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date");

                            b1.Property<TimeSpan>("UtcOffset")
                                .HasColumnType("interval");

                            b1.HasKey("TransportRequestId");

                            b1.ToTable("transport_requests");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestId");

                            b1.OwnsMany("Nagomi.Api.Domain.WeekdaySchedule", "WeekdaySchedules", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("DayOfWeek")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)");

                                    b2.Property<TimeOnly>("OutboundAppointmentTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly?>("OutboundPickupTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly?>("OutboundStartTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<Guid>("RecurrencePatternTransportRequestId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("ReturnPickupNextDay")
                                        .HasColumnType("boolean");

                                    b2.Property<TimeOnly?>("ReturnPickupTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<bool>("ReturnPickupTimePending")
                                        .HasColumnType("boolean");

                                    b2.HasKey("Id");

                                    b2.HasIndex("RecurrencePatternTransportRequestId");

                                    b2.ToTable("recurrence_weekday_schedules", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("RecurrencePatternTransportRequestId");
                                });

                            b1.Navigation("WeekdaySchedules");
                        });

                    b.OwnsOne("Nagomi.Api.Domain.TransportReasonSnapshot", "Reason", b1 =>
                        {
                            b1.Property<Guid>("TransportRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.HasKey("TransportRequestId");

                            b1.ToTable("transport_requests");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestId");
                        });

                    b.OwnsOne("Nagomi.Api.Domain.LocationSnapshot", "DefaultDestination", b1 =>
                        {
                            b1.Property<Guid>("TransportRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AdditionalDetails")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Block")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("Door")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("FacilityPublicId")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<string>("Floor")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<decimal?>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)");

                            b1.Property<decimal?>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)");

                            b1.Property<string>("Municipality")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)");

                            b1.Property<string>("MunicipalityCode")
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)");

                            b1.Property<string>("Name")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("Number")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("Observations")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("OfficialCode")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Phone")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Province")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)");

                            b1.Property<string>("ProvinceCode")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)");

                            b1.Property<string>("Staircase")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("Street")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.HasKey("TransportRequestId");

                            b1.ToTable("transport_requests");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestId");
                        });

                    b.OwnsOne("Nagomi.Api.Domain.LocationSnapshot", "DefaultOrigin", b1 =>
                        {
                            b1.Property<Guid>("TransportRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AdditionalDetails")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Block")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("Door")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("FacilityPublicId")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<string>("Floor")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<decimal?>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)");

                            b1.Property<decimal?>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)");

                            b1.Property<string>("Municipality")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)");

                            b1.Property<string>("MunicipalityCode")
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)");

                            b1.Property<string>("Name")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("Number")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("Observations")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("OfficialCode")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Phone")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Province")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)");

                            b1.Property<string>("ProvinceCode")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)");

                            b1.Property<string>("Staircase")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("Street")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.HasKey("TransportRequestId");

                            b1.ToTable("transport_requests");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestId");
                        });

                    b.OwnsOne("Nagomi.Api.Domain.TransportRequirements", "Requirements", b1 =>
                        {
                            b1.Property<Guid>("TransportRequestId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("BariatricRequired")
                                .HasColumnType("boolean");

                            b1.Property<bool>("CompanionRequired")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsolationRequired")
                                .HasColumnType("boolean");

                            b1.Property<bool>("MedicalStaffRequired")
                                .HasColumnType("boolean");

                            b1.Property<string>("Mobility")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<decimal?>("OxygenConcentrationPercent")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)");

                            b1.Property<decimal?>("OxygenFlowLitresPerMinute")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)");

                            b1.Property<bool>("RequiresOxygen")
                                .HasColumnType("boolean");

                            b1.Property<bool>("StairsAssistanceRequired")
                                .HasColumnType("boolean");

                            b1.HasKey("TransportRequestId");

                            b1.ToTable("transport_requests");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestId");
                        });

                    b.Navigation("DefaultDestination");

                    b.Navigation("DefaultOrigin");

                    b.Navigation("Patient");

                    b.Navigation("Reason");

                    b.Navigation("Recurrence");

                    b.Navigation("Requirements")
                        .IsRequired();
                });

            modelBuilder.Entity("Nagomi.Api.Features.Audit.AuditChange", b =>
                {
                    b.HasOne("Nagomi.Api.Features.Audit.AuditEntry", null)
                        .WithMany("Changes")
                        .HasForeignKey("AuditEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nagomi.Api.Domain.Journey", b =>
                {
                    b.Navigation("StatusEvents");
                });

            modelBuilder.Entity("Nagomi.Api.Domain.TransportRequest", b =>
                {
                    b.Navigation("Journeys");
                });

            modelBuilder.Entity("Nagomi.Api.Features.Audit.AuditEntry", b =>
                {
                    b.Navigation("Changes");
                });
#pragma warning restore 612, 618
        }
    }
}
